### ISSUE TITLE
Does not compile if UNICODE is defined. 

### ISSUE THREAD

**Issue by Remotion** [ltjax/file_monitor#16]
https://github.com/ltjax/file_monitor/blob/b3bc8ceda0528d4022896e8046678ba6dfd20b9e/source/file_monitor/win_monitor.cpp#L42

CreateFile will be replaced by CreateFileW, CreateEvent will be replaced by CreateEventW and compilation fails this way.

**Comment by ltjax** [comment]
Right as well, of course. I'll fix it.
